### ISSUE TITLE
Support FFZ donor icons and custom badges

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#219]

**Comment by Zelakto** [comment]
Seems like this is now broken. RIP.

**Comment by SirStendec** [comment]
We at FrankerFaceZ recently created a new API endpoint for badge data since it's actually being tracked in our database now. You can get all the relevant information from https://api.frankerfacez.com/v1/badges or if you'd only like one kind of badge at a time you can use https://api.frankerfacez.com/v1/badge/supporter

Please feel free to contact me here, on Twitter, or on Twitch if you have any questions or issues integrating FFZ data into your product.

**Comment by mccxiv** [comment]
Thanks @SirStendec 

Question: will you be removing http://cdn.frankerfacez.com/script/donors.txt ?

**Comment by SirStendec** [comment]
Yes. That file isn't currently up to date and it's only still there as I've forgotten about it. For your current needs, you can just grab https://api.frankerfacez.com/v1/badge/supporter and get ["users"][3] from the object it returns to get your flat array of ffz supporters.
