### ISSUE TITLE
Substring of word targeted as highlight

### ISSUE THREAD

**Issue by notdom** [mccxiv/tc#334]
So I have my name "dom" set as a highlight for TC, and whenever someone types a word that has the substring "dom" in it, it triggers a highlight for the substring instead of only looking for my name by itself.

ex. a chatter sending a message with the words domination, random, abdomen, or boredom, etc. pings me.

Not sure if this is the preferred behavior that you want or possible bug. I kinda want to tackle the problem myself to improve my beginner skill, and will keep you posted if I figure it out (unless you beat me to it, then that works too haha).

**Comment by scsddeputy** [comment]
the functionality is written so that will happen, it is a Regex Expression so if it finds a match of the highlighted phrase, then it will trigger. 

If you only wanted it to trigger when the word "dom" is by itself, then you would need to rewrite the function in 'src/tc-renderer/ng/providers/highlights.js'. if you look at the 'test' function on that file, the part after the if statement is where the regex function is
