### ISSUE TITLE
Password page: Text misleading

### ISSUE THREAD

**Issue by m1ga** [mccxiv/tc#442]
Why does it say `Below is your chat password, copy & paste the whole thing.` ?

Took me some time to figure out that I don't need to copy the _whole thing_ but just everything next to `oauth:`. Should be a bit clearer or put another div with a border around the password.

**Comment by mccxiv** [comment]
Actually the text is right, you need everything including `oauth:`. We have some fallback in the code that adds it for you if you didn't copy it, but the correct behavior is to copy paste it all. 

Are you saying it's not working correctly in the application? I will look into this.

Another thing I should do is just have a "Copy" button in the website so that you don't need to manually copy text

**Comment by m1ga** [comment]
The -> arrow in the login window never turns into the clickable state, I only can use enter to submit the name+password. And when I've tried the whole text it always stayed at "disconnected" and in a login loop. Only when I've tried it without the `oauth:` it worked (still the arrow was disabled). 

Using Fedora Linux with the latest tc 13 appimage

**Comment by mccxiv** [comment]
Thanks for the report
