### ISSUE TITLE
Inline mod command improvements

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#463]
- [x] The inline purge button becomes a ban or 24hr button if the user has been timed out
- [x] The chat stops scrolling if you hover the buttons, and resumes scrolling once you un-hover
- [x] Unrelated but needs fixing: Errors in console when on the Add Channel tab

**Comment by camalot** [comment]
I may have some time tonight (or this weekend) to take a look at these. 

there is already a ban button there. these behave just like the 3 buttons that are in the `user-panel`. A possible improvement would be to allow configuration of how long to timeout for. 

I don't think changing to a ban, if they have been timedout/purged is ideal. There are many times that I have purged a person more than one time, or even timed them out more than once.

**Comment by mccxiv** [comment]
I'm starting on it now, don't worry (unless you did it already?)

**Comment by camalot** [comment]
I have not, but can you please clarify the "inline purge becomes a ban"? because there are many cases where I would not want to perma ban, or even 24 hour ban, just because I timed out someone already.

The scroll one, that one is actually a really good feature though. I have accidentally banned the wrong person in active chats because of scrolling.

**Comment by camalot** [comment]
Another option, would be to allow people to choose the amount of time to `timeout`, and `purge`, and if they want to show each of the actions: `purge`, `timeout`, `ban`

here is a mockup I started throwing together in my fork. 

![image](https://user-images.githubusercontent.com/171452/45931010-2893ab80-bf2d-11e8-853f-e21c6c5928db.png)

I am suggesting something like this, over what is currently in `master` because the way it is, it does not work for me.

**Comment by mccxiv** [comment]
I have some time this weekend. The goal is to add this and make a release

**Comment by mccxiv** [comment]
Version 1 has no setting, but if we get feedback then we can add an on option in the settings menu
